"""add diagnosis analysis fields

Revision ID: 84431d117900
Revises: 
Create Date: 2026-09-03 20:17:47.974059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84431d117900'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('result_status', sa.String(length=20), nullable=False))
    op.add_column('diagnoses', sa.Column('findings_json', sa.Text(), nullable=False))
    op.add_column('diagnoses', sa.Column('all_predictions_json', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'all_predictions_json')
    op.drop_column('diagnoses', 'findings_json')
    op.drop_column('diagnoses', 'result_status')
    # ### end Alembic commands ###
