import { ArrowRight, BrainCircuit, CheckCircle2, FileText, HeartPulse, LockKeyhole, ScanLine, Users, Workflow } from "lucide-react";
import { useNavigate } from "react-router-dom";

const features = [
  [ScanLine, "AI-assisted X-ray analysis", "Review structured chest X-ray findings from the DenseNet121 model."],
  [BrainCircuit, "14-condition classification", "See probability values and top predictions in one focused result view."],
  [Users, "Patient management", "Keep patient profiles and longitudinal analysis history organized."],
  [FileText, "Automated reports", "Generate consistent PDF reports for physician review and documentation."],
  [Workflow, "Human-in-the-loop", "Physicians remain responsible for interpretation and clinical decisions."],
  [LockKeyhole, "Secure access", "JWT authentication and ownership checks protect physician workspaces."],
];

export default function Landing() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <header className="absolute inset-x-0 top-0 z-10 border-b border-white/10">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-8">
          <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400 text-slate-950"><HeartPulse size={22} /></div><div><p className="font-bold tracking-tight">MedVision AI</p><p className="text-xs text-cyan-200">Clinical imaging intelligence</p></div></div>
          <button onClick={() => navigate("/login")} className="rounded-xl border border-white/20 px-4 py-2 text-sm font-semibold transition hover:bg-white/10">Physician login</button>
        </div>
      </header>

      <main>
        <section className="relative overflow-hidden px-6 pb-24 pt-40 lg:px-8 lg:pb-32">
          <div className="absolute -right-32 top-20 h-96 w-96 rounded-full bg-cyan-500/20 blur-3xl" /><div className="absolute -left-40 bottom-0 h-96 w-96 rounded-full bg-blue-600/20 blur-3xl" />
          <div className="relative mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[1.1fr_.9fr]">
            <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-3 py-1 text-xs font-semibold uppercase tracking-[.18em] text-cyan-200"><span className="h-2 w-2 rounded-full bg-cyan-300" /> Built for physician review</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.05] tracking-tight sm:text-6xl">Make every chest X-ray review more organized.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">MedVision AI helps physicians manage patient records, explore AI-assisted chest X-ray findings, and produce review-ready medical reports in one secure workspace.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => navigate("/login")} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 transition hover:bg-cyan-300">Get started <ArrowRight size={18} /></button><a href="#how-it-works" className="rounded-xl border border-white/20 px-5 py-3 font-semibold text-slate-200 transition hover:bg-white/10">See how it works</a></div><p className="mt-6 text-sm text-slate-400">AI-assisted assessment — not a definitive diagnosis.</p></div>
            <div className="relative"><div className="rounded-[2rem] border border-white/15 bg-white/[.07] p-4 shadow-2xl shadow-cyan-950/40 backdrop-blur"><div className="rounded-[1.5rem] bg-slate-900 p-6"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-300">Analysis workspace</span><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">READY FOR REVIEW</span></div><div className="mt-6 grid grid-cols-[1fr_auto] gap-5"><div className="flex min-h-64 items-center justify-center rounded-2xl bg-gradient-to-br from-slate-800 to-slate-950"><div className="relative h-44 w-36 rounded-[50%] border border-cyan-200/50 bg-gradient-to-br from-slate-300/40 via-slate-100/10 to-slate-800/50 shadow-[inset_0_0_40px_rgba(34,211,238,.18)]"><span className="absolute left-1/2 top-5 h-28 w-px -translate-x-1/2 bg-cyan-200/40" /><span className="absolute left-7 right-7 top-1/2 border-t border-cyan-200/30" /></div></div><div className="space-y-3"><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-400">Top finding</p><p className="mt-1 font-semibold text-white">Review potential findings</p></div><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-400">Model</p><p className="mt-1 font-semibold text-cyan-200">DenseNet121</p></div><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-slate-400">Conditions</p><p className="mt-1 font-semibold text-white">14 classes</p></div></div></div></div></div><div className="absolute -bottom-5 -left-5 flex items-center gap-3 rounded-2xl border border-white/15 bg-slate-800/90 px-4 py-3 shadow-xl"><CheckCircle2 className="text-emerald-300" size={20} /><span className="text-sm font-semibold">Physician-reviewed workflow</span></div></div>
          </div>
        </section>

        <section className="bg-white px-6 py-24 text-slate-900 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-cyan-700">A clearer clinical workspace</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Turn disconnected steps into a thoughtful review loop.</h2><p className="mt-4 leading-7 text-slate-600">The platform brings patient context, model output, physician oversight, and reporting together without presenting automation as a clinical verdict.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, description]) => <article key={title} className="rounded-2xl border border-slate-200 bg-slate-50 p-6 transition hover:-translate-y-1 hover:border-cyan-200 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-cyan-100 text-cyan-700"><Icon size={21} /></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></div></section>

        <section id="how-it-works" className="bg-slate-100 px-6 py-24 text-slate-900 lg:px-8"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.18em] text-cyan-700">How it works</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">A simple path from image to insight</h2></div><div className="mt-12 grid gap-4 md:grid-cols-5">{["Physician login", "Select or create patient", "Upload X-ray", "AI-assisted analysis", "Review and report"].map((step, index) => <div key={step} className="relative rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm"><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-full bg-cyan-700 text-sm font-bold text-white">{index + 1}</span><p className="mt-4 text-sm font-semibold">{step}</p>{index < 4 && <ArrowRight className="absolute -right-4 top-1/2 z-10 hidden -translate-y-1/2 text-cyan-500 md:block" size={18} />}</div>)}</div></div></section>

        <section className="bg-cyan-700 px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-cyan-100">Safety by design</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">The physician stays in the loop.</h2><p className="mt-4 max-w-xl leading-7 text-cyan-50">DenseNet121 provides a multi-label classification aid across 14 chest X-ray conditions. Its probabilities and findings are supporting information for a qualified professional, not a substitute for examination, history, or clinical judgment.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 p-6"><div className="flex gap-3"><LockKeyhole className="mt-1 shrink-0 text-cyan-100" size={22} /><p className="text-sm leading-6 text-cyan-50">Review every AI result, confirm the patient context, and make clinical decisions using professional judgment and applicable protocols.</p></div></div></div></section>
      </main>
      <footer className="border-t border-white/10 bg-slate-950 px-6 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between"><p className="font-semibold text-white">MedVision AI</p><p>AI-assisted medical report management for physician review.</p><button onClick={() => navigate("/login")} className="text-left text-cyan-300 hover:text-cyan-200 sm:text-right">Open physician workspace →</button></div></footer>
    </div>
  );
}
