import { useState } from "react";
import { ArrowLeft, HeartPulse } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";

export default function Register() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ full_name: "", email: "", password: "" });
  const [state, setState] = useState({ loading: false, error: "", success: "" });
  const submit = async (event) => {
    event.preventDefault(); setState({ loading: true, error: "", success: "" });
    try { await api.post("/auth/register", form); setState({ loading: false, error: "", success: "Account created. You can now sign in." }); setForm({ full_name: "", email: "", password: "" }); } catch (error) { setState({ loading: false, error: error.response?.data?.detail || "Unable to create the account.", success: "" }); }
  };
  return <div className="flex min-h-screen items-center justify-center bg-slate-50 px-4 py-10"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><button onClick={() => navigate("/login")} className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-cyan-700"><ArrowLeft size={16} /> Back to login</button><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-600 text-white"><HeartPulse size={21} /></div><div><h1 className="font-bold text-slate-900">Create physician account</h1><p className="text-xs text-slate-500">MedVision AI workspace access</p></div></div><form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-semibold text-slate-700">Full name<input required minLength={2} value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-cyan-500" /></label><label className="block text-sm font-semibold text-slate-700">Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-cyan-500" /></label><label className="block text-sm font-semibold text-slate-700">Password<input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-cyan-500" /><span className="mt-1 block text-xs font-normal text-slate-400">At least 8 characters.</span></label>{state.error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}{state.success && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{state.success}</p>}<button disabled={state.loading} className="w-full rounded-xl bg-cyan-600 px-4 py-3 font-bold text-white transition hover:bg-cyan-700 disabled:cursor-not-allowed disabled:opacity-60">{state.loading ? "Creating account…" : "Create account"}</button></form><p className="mt-6 text-xs leading-5 text-slate-500">New registrations receive the PHYSICIAN role. Administrative access is assigned separately.</p></div></div>;
}
